<?php
$enabled = $block->statusEnabled();
if ($enabled==1):
    $stockStatus = $block->currentProductStatus();
    $stock = $stockStatus['stock'];
?>
<div class="stockstatus">
<div class="progress-wrapper">
	<div class="progress-header">
		<span class="progress-icon"></span>
		<label class="progress-label"> </label>
	</div>
	<div class="progress-bar"></div>
</div>
</div>
<script>
let stockLevel = <?= /* @noEscape */ $stock ?>;
const progressLabel = document.querySelector(".progress-label");
const progressBar = document.querySelector(".progress-bar");
const progressIcon = document.querySelector(".progress-icon");
const progressBarInner = document.createElement("div");
progressBarInner.id = "progress-bar-inner";
progressBar.appendChild(progressBarInner);
function setProgress(stockLevel) {
	progressBarInner.style.width = stockLevel + "%";
	if (stockLevel > <?= /* @noEscape */ $stockStatus['mediumStockQty'] ?>) {
		progressBarInner.style.backgroundColor = "<?= /* @noEscape */ $stockStatus['hightStockColour'] ?>";
		progressLabel.innerHTML = "<?= /* @noEscape */ str_replace("%", $stock, $stockStatus['hightStockError']) ?>";
		progressIcon.style.content = "url('<?= /* @noEscape */ $block->getViewFileUrl('Mindsprint_StockStatus::images/green-stock.svg'); ?>')";
	} else if (stockLevel > <?= /* @noEscape */ $stockStatus['lowStockQty'] ?> && stockLevel <= <?= /* @noEscape */ $stockStatus['mediumStockQty'] ?>) {
		progressBarInner.style.backgroundColor = "<?= /* @noEscape */ $stockStatus['mediumStockColour'] ?>";
		progressLabel.innerHTML = "<?= /* @noEscape */ str_replace("%", $stock, $stockStatus['mediumstockError']) ?>";
		progressIcon.style.content = "url('<?= /* @noEscape */ $block->getViewFileUrl('Mindsprint_StockStatus::images/orange-stock.svg'); ?>')";
	} else if (stockLevel >= 1 && stockLevel <= <?= /* @noEscape */ $stockStatus['lowStockQty'] ?>) {
		progressBarInner.style.backgroundColor = "<?= /* @noEscape */ $stockStatus['lowStockColour'] ?>";
		progressLabel.innerHTML = "<?= /* @noEscape */ str_replace("%", $stock, $stockStatus['lowstockError']) ?>";
		progressIcon.style.content = "url('<?= /* @noEscape */ $block->getViewFileUrl('Mindsprint_StockStatus::images/red-stock.svg'); ?>')";
	} else {
		progressBarInner.style.backgroundColor = "<?= /* @noEscape */ $stockStatus['outofStockColour'] ?>";
		progressLabel.innerHTML = "<?= /* @noEscape */ str_replace("%", $stock, $stockStatus['outofStockError']) ?>";
		progressIcon.style.content = "url('<?= /* @noEscape */ $block->getViewFileUrl('Mindsprint_StockStatus::images/grey-stock.svg'); ?>')";
	}
}
setProgress(stockLevel);
</script>
<?php endif; ?>
